# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.inputs

defmodule Vllm.Inputs do
  @moduledoc """
  Submodule bindings for `vllm.inputs`.

  ## Version

  - Requested: 0.14.0
  - Observed at generation: 0.14.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Vllm.Inputs.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Vllm.Inputs.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Vllm.Inputs.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Vllm.Inputs.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "vllm.inputs"
  @doc false
  def __snakebridge_library__, do: "vllm"

  @doc """
  Built-in mutable sequence.

  If no argument is given, the constructor creates a new empty list.
  The argument must be an iterable if specified.

  ## Returns

  - `list(term())`
  """
  @spec __all__() :: {:ok, list(term())} | {:error, Snakepit.Error.t()}
  def __all__() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, :__all__)
  end

  @doc """
  Python binding for `vllm.inputs.build_explicit_enc_dec_prompt`.

  ## Parameters

  - `encoder_prompt` (term())
  - `decoder_prompt` (term() | nil)
  - `mm_processor_kwargs` (term() default: None)

  ## Returns

  - `term()`
  """
  @spec build_explicit_enc_dec_prompt(term(), term() | nil) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec build_explicit_enc_dec_prompt(term(), term() | nil, keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec build_explicit_enc_dec_prompt(term(), term() | nil, term()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec build_explicit_enc_dec_prompt(term(), term() | nil, term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def build_explicit_enc_dec_prompt(encoder_prompt, decoder_prompt) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :build_explicit_enc_dec_prompt,
      [encoder_prompt, decoder_prompt],
      []
    )
  end

  def build_explicit_enc_dec_prompt(encoder_prompt, decoder_prompt, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :build_explicit_enc_dec_prompt,
      [encoder_prompt, decoder_prompt],
      opts
    )
  end

  def build_explicit_enc_dec_prompt(encoder_prompt, decoder_prompt, mm_processor_kwargs) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :build_explicit_enc_dec_prompt,
      [encoder_prompt, decoder_prompt, mm_processor_kwargs],
      []
    )
  end

  def build_explicit_enc_dec_prompt(encoder_prompt, decoder_prompt, mm_processor_kwargs, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :build_explicit_enc_dec_prompt,
      [encoder_prompt, decoder_prompt, mm_processor_kwargs],
      opts
    )
  end

  @doc """
  Represent a PEP 604 union type

  E.g. for int | str

  ## Returns

  - `term()`
  """
  @spec decoder_only_inputs() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def decoder_only_inputs() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "DecoderOnlyInputs")
  end

  @doc """
  Construct [`EmbedsInputs`][vllm.inputs.data.EmbedsInputs] from optional

  values.

  ## Parameters

  - `prompt_embeds` (term())
  - `cache_salt` (term() default: None)

  ## Returns

  - `term()`
  """
  @spec embeds_inputs(term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec embeds_inputs(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec embeds_inputs(term(), term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec embeds_inputs(term(), term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def embeds_inputs(prompt_embeds) do
    SnakeBridge.Runtime.call(__MODULE__, :embeds_inputs, [prompt_embeds], [])
  end

  def embeds_inputs(prompt_embeds, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :embeds_inputs, [prompt_embeds], opts)
  end

  def embeds_inputs(prompt_embeds, cache_salt) do
    SnakeBridge.Runtime.call(__MODULE__, :embeds_inputs, [prompt_embeds, cache_salt], [])
  end

  def embeds_inputs(prompt_embeds, cache_salt, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :embeds_inputs, [prompt_embeds, cache_salt], opts)
  end

  @doc """
  Represent a PEP 604 union type

  E.g. for int | str

  ## Returns

  - `term()`
  """
  @spec processor_inputs() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def processor_inputs() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "ProcessorInputs")
  end

  @doc """
  Represent a PEP 604 union type

  E.g. for int | str

  ## Returns

  - `term()`
  """
  @spec prompt_type() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def prompt_type() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "PromptType")
  end

  @doc """
  Represent a PEP 604 union type

  E.g. for int | str

  ## Returns

  - `term()`
  """
  @spec singleton_inputs() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def singleton_inputs() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "SingletonInputs")
  end

  @doc """
  Represent a PEP 604 union type

  E.g. for int | str

  ## Returns

  - `term()`
  """
  @spec singleton_prompt() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def singleton_prompt() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "SingletonPrompt")
  end

  @doc """
  Python binding for `vllm.inputs.to_enc_dec_tuple_list`.

  ## Parameters

  - `enc_dec_prompts` (term())

  ## Returns

  - `list({term(), term() | nil})`
  """
  @spec to_enc_dec_tuple_list(term(), keyword()) ::
          {:ok, list({term(), term() | nil})} | {:error, Snakepit.Error.t()}
  def to_enc_dec_tuple_list(enc_dec_prompts, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :to_enc_dec_tuple_list, [enc_dec_prompts], opts)
  end

  @doc """
  Construct [`TokenInputs`][vllm.inputs.data.TokenInputs] from optional

  values.

  ## Parameters

  - `prompt_token_ids` (list(integer()))
  - `cache_salt` (term() default: None)

  ## Returns

  - `term()`
  """
  @spec token_inputs(list(integer())) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec token_inputs(list(integer()), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec token_inputs(list(integer()), term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec token_inputs(list(integer()), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def token_inputs(prompt_token_ids) do
    SnakeBridge.Runtime.call(__MODULE__, :token_inputs, [prompt_token_ids], [])
  end

  def token_inputs(prompt_token_ids, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :token_inputs, [prompt_token_ids], opts)
  end

  def token_inputs(prompt_token_ids, cache_salt) do
    SnakeBridge.Runtime.call(__MODULE__, :token_inputs, [prompt_token_ids, cache_salt], [])
  end

  def token_inputs(prompt_token_ids, cache_salt, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :token_inputs, [prompt_token_ids, cache_salt], opts)
  end

  @doc """
  Zip encoder and decoder prompts together into a list of

  [`ExplicitEncoderDecoderPrompt`][vllm.inputs.data.ExplicitEncoderDecoderPrompt]
  instances.

  `mm_processor_kwargs` may also be provided; if a dict is passed, the same
  dictionary will be used for every encoder/decoder prompt. If an iterable is
  provided, it will be zipped with the encoder/decoder prompts.

  ## Parameters

  - `enc_prompts` (term())
  - `dec_prompts` (term())
  - `mm_processor_kwargs` (term() default: None)

  ## Returns

  - `list(term())`
  """
  @spec zip_enc_dec_prompts(term(), term()) :: {:ok, list(term())} | {:error, Snakepit.Error.t()}
  @spec zip_enc_dec_prompts(term(), term(), keyword()) ::
          {:ok, list(term())} | {:error, Snakepit.Error.t()}
  @spec zip_enc_dec_prompts(term(), term(), term()) ::
          {:ok, list(term())} | {:error, Snakepit.Error.t()}
  @spec zip_enc_dec_prompts(term(), term(), term(), keyword()) ::
          {:ok, list(term())} | {:error, Snakepit.Error.t()}
  def zip_enc_dec_prompts(enc_prompts, dec_prompts) do
    SnakeBridge.Runtime.call(__MODULE__, :zip_enc_dec_prompts, [enc_prompts, dec_prompts], [])
  end

  def zip_enc_dec_prompts(enc_prompts, dec_prompts, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :zip_enc_dec_prompts, [enc_prompts, dec_prompts], opts)
  end

  def zip_enc_dec_prompts(enc_prompts, dec_prompts, mm_processor_kwargs) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :zip_enc_dec_prompts,
      [enc_prompts, dec_prompts, mm_processor_kwargs],
      []
    )
  end

  def zip_enc_dec_prompts(enc_prompts, dec_prompts, mm_processor_kwargs, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :zip_enc_dec_prompts,
      [enc_prompts, dec_prompts, mm_processor_kwargs],
      opts
    )
  end
end
