# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.connections
# Python class: HTTPConnection

defmodule Vllm.Connections.HTTPConnection do
  @moduledoc """
  Helper class to send HTTP requests.
  """
  def __snakebridge_python_name__, do: "vllm.connections"
  def __snakebridge_python_class__, do: "HTTPConnection"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `reuse_client` (boolean() keyword-only default: True)
  """
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  @doc """
  Python method `HTTPConnection._headers`.

  ## Parameters

  - `extras` (String.t())

  ## Returns

  - `term()`
  """
  @spec _headers(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _headers(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_headers, [], opts)
  end

  @doc """
  Python method `HTTPConnection._validate_http_url`.

  ## Parameters

  - `url` (String.t())

  ## Returns

  - `term()`
  """
  @spec _validate_http_url(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _validate_http_url(ref, url, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_validate_http_url, [url], opts)
  end

  @doc """
  Python method `HTTPConnection.async_download_file`.

  ## Parameters

  - `url` (String.t())
  - `save_path` (term())
  - `timeout` (term() keyword-only default: None)
  - `chunk_size` (integer() keyword-only default: 128)

  ## Returns

  - `term()`
  """
  @spec async_download_file(SnakeBridge.Ref.t(), String.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def async_download_file(ref, url, save_path, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :async_download_file, [url, save_path], opts)
  end

  @doc """
  Python method `HTTPConnection.async_get_bytes`.

  ## Parameters

  - `url` (String.t())
  - `timeout` (term() keyword-only default: None)
  - `allow_redirects` (boolean() keyword-only default: True)

  ## Returns

  - `binary()`
  """
  @spec async_get_bytes(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, binary()} | {:error, Snakepit.Error.t()}
  def async_get_bytes(ref, url, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :async_get_bytes, [url], opts)
  end

  @doc """
  Python method `HTTPConnection.async_get_json`.

  ## Parameters

  - `url` (String.t())
  - `timeout` (term() keyword-only default: None)

  ## Returns

  - `String.t()`
  """
  @spec async_get_json(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def async_get_json(ref, url, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :async_get_json, [url], opts)
  end

  @doc """
  Python method `HTTPConnection.async_get_text`.

  ## Parameters

  - `url` (String.t())
  - `timeout` (term() keyword-only default: None)

  ## Returns

  - `String.t()`
  """
  @spec async_get_text(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def async_get_text(ref, url, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :async_get_text, [url], opts)
  end

  @doc """
  Python method `HTTPConnection.download_file`.

  ## Parameters

  - `url` (String.t())
  - `save_path` (term())
  - `timeout` (term() keyword-only default: None)
  - `chunk_size` (integer() keyword-only default: 128)

  ## Returns

  - `term()`
  """
  @spec download_file(SnakeBridge.Ref.t(), String.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def download_file(ref, url, save_path, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :download_file, [url, save_path], opts)
  end

  @doc """
  Python method `HTTPConnection.get_async_client`.

  ## Returns

  - `term()`
  """
  @spec get_async_client(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def get_async_client(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_async_client, [], opts)
  end

  @doc """
  Python method `HTTPConnection.get_async_response`.

  ## Parameters

  - `url` (String.t())
  - `timeout` (term() keyword-only default: None)
  - `extra_headers` (term() keyword-only default: None)
  - `allow_redirects` (boolean() keyword-only default: True)

  ## Returns

  - `term()`
  """
  @spec get_async_response(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def get_async_response(ref, url, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_async_response, [url], opts)
  end

  @doc """
  Python method `HTTPConnection.get_bytes`.

  ## Parameters

  - `url` (String.t())
  - `timeout` (term() keyword-only default: None)
  - `allow_redirects` (boolean() keyword-only default: True)

  ## Returns

  - `binary()`
  """
  @spec get_bytes(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, binary()} | {:error, Snakepit.Error.t()}
  def get_bytes(ref, url, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_bytes, [url], opts)
  end

  @doc """
  Python method `HTTPConnection.get_json`.

  ## Parameters

  - `url` (String.t())
  - `timeout` (term() keyword-only default: None)

  ## Returns

  - `String.t()`
  """
  @spec get_json(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def get_json(ref, url, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_json, [url], opts)
  end

  @doc """
  Python method `HTTPConnection.get_response`.

  ## Parameters

  - `url` (String.t())
  - `stream` (boolean() keyword-only default: False)
  - `timeout` (term() keyword-only default: None)
  - `extra_headers` (term() keyword-only default: None)
  - `allow_redirects` (boolean() keyword-only default: True)

  ## Returns

  - `term()`
  """
  @spec get_response(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def get_response(ref, url, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_response, [url], opts)
  end

  @doc """
  Python method `HTTPConnection.get_sync_client`.

  ## Returns

  - `term()`
  """
  @spec get_sync_client(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def get_sync_client(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_sync_client, [], opts)
  end

  @doc """
  Python method `HTTPConnection.get_text`.

  ## Parameters

  - `url` (String.t())
  - `timeout` (term() keyword-only default: None)

  ## Returns

  - `String.t()`
  """
  @spec get_text(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def get_text(ref, url, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_text, [url], opts)
  end
end
