# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.outputs
# Python class: PoolingOutput

defmodule Vllm.Outputs.PoolingOutput do
  @moduledoc """
  The output data of one pooling output of a request.



  ## Parameters

  - `data` - The extracted hidden states.
  """
  def __snakebridge_python_name__, do: "vllm.outputs"
  def __snakebridge_python_class__, do: "PoolingOutput"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `data` (term())
  """
  @spec new(term(), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(data, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [data], opts)
  end
end
