# Generated by SnakeBridge v0.16.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.plugins

defmodule Vllm.Plugins do
  @moduledoc """
  Submodule bindings for `vllm.plugins`.

  ## Version

  - Requested: 0.14.0
  - Observed at generation: 0.14.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Vllm.Plugins.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Vllm.Plugins.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Vllm.Plugins.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Vllm.Plugins.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "vllm.plugins"
  @doc false
  def __snakebridge_library__, do: "vllm"

  @doc """
  Python module attribute `vllm.plugins.DEFAULT_PLUGINS_GROUP`.

  ## Returns

  - `String.t()`
  """
  @spec default_plugins_group() :: {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def default_plugins_group() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "DEFAULT_PLUGINS_GROUP")
  end

  @doc """
  Python module attribute `vllm.plugins.IO_PROCESSOR_PLUGINS_GROUP`.

  ## Returns

  - `String.t()`
  """
  @spec io_processor_plugins_group() :: {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def io_processor_plugins_group() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "IO_PROCESSOR_PLUGINS_GROUP")
  end

  @doc """
  WARNING: plugins can be loaded for multiple times in different

  processes. They should be designed in a way that they can be loaded
  multiple times without causing issues.

  ## Returns

  - `term()`
  """
  @spec load_general_plugins(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def load_general_plugins(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :load_general_plugins, [], opts)
  end

  @doc """
  Python binding for `vllm.plugins.load_plugins_by_group`.

  ## Parameters

  - `group` (String.t())

  ## Returns

  - `%{optional(String.t()) => term()}`
  """
  @spec load_plugins_by_group(String.t(), keyword()) ::
          {:ok, %{optional(String.t()) => term()}} | {:error, Snakepit.Error.t()}
  def load_plugins_by_group(group, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :load_plugins_by_group, [group], opts)
  end

  @doc """
  Python module attribute `vllm.plugins.logger`.

  ## Returns

  - `term()`
  """
  @spec logger() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def logger() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, :logger)
  end

  @doc """
  Python module attribute `vllm.plugins.PLATFORM_PLUGINS_GROUP`.

  ## Returns

  - `String.t()`
  """
  @spec platform_plugins_group() :: {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def platform_plugins_group() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "PLATFORM_PLUGINS_GROUP")
  end

  @doc """
  Python module attribute `vllm.plugins.plugins_loaded`.

  ## Returns

  - `boolean()`
  """
  @spec plugins_loaded() :: {:ok, boolean()} | {:error, Snakepit.Error.t()}
  def plugins_loaded() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, :plugins_loaded)
  end

  @doc """
  Python module attribute `vllm.plugins.STAT_LOGGER_PLUGINS_GROUP`.

  ## Returns

  - `String.t()`
  """
  @spec stat_logger_plugins_group() :: {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def stat_logger_plugins_group() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "STAT_LOGGER_PLUGINS_GROUP")
  end
end
