# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.sampling_params

defmodule Vllm.SamplingParams.Module do
  @moduledoc """
  Sampling parameters for text generation.

  ## Version

  - Requested: 0.14.0
  - Observed at generation: 0.14.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Vllm.SamplingParams.Module.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Vllm.SamplingParams.Module.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Vllm.SamplingParams.Module.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Vllm.SamplingParams.Module.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "vllm.sampling_params"
  @doc false
  def __snakebridge_library__, do: "vllm"

  @doc """
  Python module attribute `vllm.sampling_params._MAX_TEMP`.

  ## Returns

  - `float()`
  """
  @spec _max_temp() :: {:ok, float()} | {:error, Snakepit.Error.t()}
  def _max_temp() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "_MAX_TEMP")
  end

  @doc """
  Python module attribute `vllm.sampling_params._SAMPLING_EPS`.

  ## Returns

  - `float()`
  """
  @spec _sampling_eps() :: {:ok, float()} | {:error, Snakepit.Error.t()}
  def _sampling_eps() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "_SAMPLING_EPS")
  end

  @doc """
  Python module attribute `vllm.sampling_params.logger`.

  ## Returns

  - `term()`
  """
  @spec logger() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def logger() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, :logger)
  end
end
