# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.sampling_params
# Python class: PydanticMsgspecMixin

defmodule Vllm.SamplingParams.PydanticMsgspecMixin do
  @moduledoc """
  Sampling parameters for text generation.
  """
  def __snakebridge_python_name__, do: "vllm.sampling_params"
  def __snakebridge_python_class__, do: "PydanticMsgspecMixin"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  Validate and convert input to msgspec.Struct instance.

  ## Parameters

  - `value` (term())

  ## Returns

  - `term()`
  """
  @spec _validate_msgspec(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _validate_msgspec(ref, value, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_validate_msgspec, [value], opts)
  end
end
