# Generated by SnakeBridge v0.16.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.logits_process
# Python class: NoBadWordsLogitsProcessor

defmodule Vllm.LogitsProcess.NoBadWordsLogitsProcessor do
  @moduledoc """
  Wrapper for Python class NoBadWordsLogitsProcessor.
  """
  def __snakebridge_python_name__, do: "vllm.logits_process"
  def __snakebridge_python_class__, do: "NoBadWordsLogitsProcessor"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `bad_words_ids` (list(list(integer())))
  """
  @spec new(list(list(integer())), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(bad_words_ids, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [bad_words_ids], opts)
  end

  @doc """
  Python method `NoBadWordsLogitsProcessor._check_token_ids_bounds`.

  ## Parameters

  - `vocab_size` (integer())

  ## Returns

  - `nil`
  """
  @spec _check_token_ids_bounds(SnakeBridge.Ref.t(), integer(), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def _check_token_ids_bounds(ref, vocab_size, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_check_token_ids_bounds, [vocab_size], opts)
  end

  @doc """
  Python method `NoBadWordsLogitsProcessor._init_word_bias`.

  ## Parameters

  - `logits` (term())

  ## Returns

  - `nil`
  """
  @spec _init_word_bias(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def _init_word_bias(ref, logits, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_init_word_bias, [logits], opts)
  end

  @spec _neutral_logit(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _neutral_logit(ref) do
    SnakeBridge.Runtime.get_attr(ref, :_NEUTRAL_LOGIT)
  end

  @spec _smallest_logit(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _smallest_logit(ref) do
    SnakeBridge.Runtime.get_attr(ref, :_SMALLEST_LOGIT)
  end
end
