# Generated by SnakeBridge v0.16.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.forward_context
# Python class: BatchDescriptor

defmodule Vllm.ForwardContext.BatchDescriptor do
  @moduledoc """
  Batch descriptor for cudagraph dispatching. We should keep the num of

  items as minimal as possible to properly and uniquely describe the padded
  batch for cudagraph.
  """
  def __snakebridge_python_name__, do: "vllm.forward_context"
  def __snakebridge_python_class__, do: "BatchDescriptor"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  Return a new dict which maps field names to their values.

  ## Returns

  - `term()`
  """
  @spec _asdict(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _asdict(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_asdict, [], opts)
  end

  @doc """
  Make a new BatchDescriptor object from a sequence or iterable

  ## Parameters

  - `iterable` (term())

  ## Returns

  - `term()`
  """
  @spec _make(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _make(ref, iterable, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_make, [iterable], opts)
  end

  @doc """
  Return a new BatchDescriptor object replacing specified fields with new values

  ## Parameters

  - `kwds` (term())

  ## Returns

  - `term()`
  """
  @spec _replace(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _replace(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_replace, [], opts)
  end

  @doc """
  Return number of occurrences of value.

  ## Parameters

  - `value` (term())

  ## Returns

  - `term()`
  """
  @spec count(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def count(ref, value, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :count, [value], opts)
  end

  @doc """
  Return first index of value.

  Raises ValueError if the value is not present.

  ## Parameters

  - `value` (term())
  - `start` (term() default: 0)
  - `stop` (term() default: 9223372036854775807)

  ## Returns

  - `term()`
  """
  @spec index(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def index(ref, value, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :index, [value] ++ List.wrap(args), opts)
  end

  @doc """
  Return a relaxed version of current batch descriptor that is still compatible

  with PIECEWISE cudagraphs (or mixed prefill-decode FA cudagraphs).

  ## Returns

  - `Vllm.ForwardContext.BatchDescriptor.t()`
  """
  @spec relax_for_mixed_batch_cudagraphs(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, Vllm.ForwardContext.BatchDescriptor.t()} | {:error, Snakepit.Error.t()}
  def relax_for_mixed_batch_cudagraphs(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :relax_for_mixed_batch_cudagraphs, [], opts)
  end

  @spec _field_defaults(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _field_defaults(ref) do
    SnakeBridge.Runtime.get_attr(ref, :_field_defaults)
  end

  @spec _fields(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _fields(ref) do
    SnakeBridge.Runtime.get_attr(ref, :_fields)
  end

  @spec has_lora(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def has_lora(ref) do
    SnakeBridge.Runtime.get_attr(ref, :has_lora)
  end

  @spec num_reqs(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def num_reqs(ref) do
    SnakeBridge.Runtime.get_attr(ref, :num_reqs)
  end

  @spec num_tokens(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def num_tokens(ref) do
    SnakeBridge.Runtime.get_attr(ref, :num_tokens)
  end

  @spec uniform(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def uniform(ref) do
    SnakeBridge.Runtime.get_attr(ref, :uniform)
  end
end
