# Generated by SnakeBridge v0.16.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.forward_context
# Python class: ForwardContext

defmodule Vllm.ForwardContext do
  @moduledoc """
  ForwardContext(no_compile_layers: dict[str, typing.Any], attn_metadata: dict[str, vllm.v1.attention.backend.AttentionMetadata] | list[dict[str, vllm.v1.attention.backend.AttentionMetadata]], virtual_engine: int, dp_metadata: vllm.forward_context.DPMetadata | None = None, cudagraph_runtime_mode: vllm.config.compilation.CUDAGraphMode = <CUDAGraphMode.NONE: 0>, batch_descriptor: vllm.forward_context.BatchDescriptor | None = None, ubatch_slices: list[vllm.v1.worker.ubatch_utils.UBatchSlice] | None = None, additional_kwargs: dict[str, typing.Any] = <factory>)
  """
  def __snakebridge_python_name__, do: "vllm.forward_context"
  def __snakebridge_python_class__, do: "ForwardContext"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `no_compile_layers` (%{optional(String.t()) => term()})
  - `attn_metadata` (term())
  - `virtual_engine` (integer())
  - `dp_metadata` (term() default: None)
  - `cudagraph_runtime_mode` (term() default: <CUDAGraphMode.NONE: 0>)
  - `batch_descriptor` (term() default: None)
  - `ubatch_slices` (term() default: None)
  - `additional_kwargs` (%{optional(String.t()) => term()} default: <factory>)
  """
  @spec new(%{optional(String.t()) => term()}, term(), integer(), list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(no_compile_layers, attn_metadata, virtual_engine, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)

    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [no_compile_layers, attn_metadata, virtual_engine] ++ List.wrap(args),
      opts
    )
  end

  @spec batch_descriptor(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def batch_descriptor(ref) do
    SnakeBridge.Runtime.get_attr(ref, :batch_descriptor)
  end

  @spec cudagraph_runtime_mode(SnakeBridge.Ref.t()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def cudagraph_runtime_mode(ref) do
    SnakeBridge.Runtime.get_attr(ref, :cudagraph_runtime_mode)
  end

  @spec dp_metadata(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def dp_metadata(ref) do
    SnakeBridge.Runtime.get_attr(ref, :dp_metadata)
  end

  @spec ubatch_slices(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ubatch_slices(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ubatch_slices)
  end
end
