# Generated by SnakeBridge v0.16.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.sequence
# Python class: IntermediateTensors

defmodule Vllm.Sequence.IntermediateTensors do
  @moduledoc """
  For all pipeline stages except the last, we need to return the hidden

  states and residuals to be sent to the next stage. This data structure
  contains the hidden states and residuals for a request.

  Each stage also needs to handle its own kv_connector_output.
  """
  def __snakebridge_python_name__, do: "vllm.sequence"
  def __snakebridge_python_class__, do: "IntermediateTensors"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `tensors` (%{optional(String.t()) => term()})
  - `kv_connector_output` (term() default: None)
  """
  @spec new(%{optional(String.t()) => term()}, list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(tensors, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [tensors] ++ List.wrap(args), opts)
  end

  @doc """
  Sequence and its related classes.

  ## Returns

  - `term()`
  """
  @spec items(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def items(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :items, [], opts)
  end
end
