# Generated by SnakeBridge v0.16.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.model_inspection

defmodule Vllm.ModelInspection do
  @moduledoc """
  Model inspection utilities for vLLM.

  ## Version

  - Requested: 0.14.0
  - Observed at generation: 0.14.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Vllm.ModelInspection.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Vllm.ModelInspection.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Vllm.ModelInspection.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Vllm.ModelInspection.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "vllm.model_inspection"
  @doc false
  def __snakebridge_library__, do: "vllm"

  @doc """
  Format indices into range notation (e.g., [0,1,2,4,5,6] -> '0-2, 4-6').

  ## Parameters

  - `indices` (list(integer()))

  ## Returns

  - `String.t()`
  """
  @spec _format_index_ranges(list(integer()), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def _format_index_ranges(indices, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :_format_index_ranges, [indices], opts)
  end

  @doc """
  Format a module tree with indentation, grouping identical layers.

  Produces output like:
    (layers): ModuleList(
      (0-27, 29-47): 47 x LlamaDecoderLayer(
        ...
      )
      (28, 48): 2 x DifferentDecoderLayer(
        ...
      )
    )

  ## Parameters

  - `module` (term())
  - `name` (String.t() default: '')
  - `indent` (integer() default: 0)

  ## Returns

  - `list(String.t())`
  """
  @spec _format_module_tree(term()) :: {:ok, list(String.t())} | {:error, Snakepit.Error.t()}
  @spec _format_module_tree(term(), keyword()) ::
          {:ok, list(String.t())} | {:error, Snakepit.Error.t()}
  @spec _format_module_tree(term(), String.t()) ::
          {:ok, list(String.t())} | {:error, Snakepit.Error.t()}
  @spec _format_module_tree(term(), String.t(), keyword()) ::
          {:ok, list(String.t())} | {:error, Snakepit.Error.t()}
  @spec _format_module_tree(term(), String.t(), integer()) ::
          {:ok, list(String.t())} | {:error, Snakepit.Error.t()}
  @spec _format_module_tree(term(), String.t(), integer(), keyword()) ::
          {:ok, list(String.t())} | {:error, Snakepit.Error.t()}
  def _format_module_tree(module) do
    SnakeBridge.Runtime.call(__MODULE__, :_format_module_tree, [module], [])
  end

  def _format_module_tree(module, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :_format_module_tree, [module], opts)
  end

  def _format_module_tree(module, name) do
    SnakeBridge.Runtime.call(__MODULE__, :_format_module_tree, [module, name], [])
  end

  def _format_module_tree(module, name, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :_format_module_tree, [module, name], opts)
  end

  def _format_module_tree(module, name, indent) do
    SnakeBridge.Runtime.call(__MODULE__, :_format_module_tree, [module, name, indent], [])
  end

  def _format_module_tree(module, name, indent, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :_format_module_tree, [module, name, indent], opts)
  end

  @doc """
  Get a signature for a child module to detect duplicates.

  ## Parameters

  - `child` (term())

  ## Returns

  - `String.t()`
  """
  @spec _get_child_signature(term(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def _get_child_signature(child, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :_get_child_signature, [child], opts)
  end

  @doc """
  Get info string for a module.

  ## Parameters

  - `module` (term())

  ## Returns

  - `String.t()`
  """
  @spec _get_module_info(term(), keyword()) :: {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def _get_module_info(module, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :_get_module_info, [module], opts)
  end

  @doc """
  Format a model into a transformers-style hierarchical string.

  ## Parameters

  - `model` (term())

  ## Returns

  - `String.t()`
  """
  @spec format_model_inspection(term(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def format_model_inspection(model, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :format_model_inspection, [model], opts)
  end
end
