# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.triton_utils
# Python class: TritonLanguagePlaceholder

defmodule Vllm.TritonUtils.TritonLanguagePlaceholder do
  @moduledoc """
  Create a module object.

  The name must be a string; the optional doc argument can have any type.
  """
  def __snakebridge_python_name__, do: "vllm.triton_utils"
  def __snakebridge_python_class__, do: "TritonLanguagePlaceholder"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.
  """
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end
end
