# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.multimodal.inputs

defmodule Vllm.Multimodal.Inputs do
  @moduledoc """
  Submodule bindings for `vllm.multimodal.inputs`.

  ## Version

  - Requested: 0.14.0
  - Observed at generation: 0.14.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Vllm.Multimodal.Inputs.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Vllm.Multimodal.Inputs.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Vllm.Multimodal.Inputs.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Vllm.Multimodal.Inputs.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "vllm.multimodal.inputs"
  @doc false
  def __snakebridge_library__, do: "vllm"

  @doc """
  A Mapping is a generic container for associating key/value

  pairs.

  This class provides concrete generic implementations of all
  methods except for __getitem__, __iter__, and __len__.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec multi_modal_data_dict(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def multi_modal_data_dict(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "MultiModalDataDict", [], opts)
  end

  @doc """
  Python binding for `vllm.multimodal.inputs.NestedTensors`.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec nested_tensors(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def nested_tensors(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "NestedTensors", [], opts)
  end
end
