# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.multimodal.inputs
# Python class: MultiModalFieldElem

defmodule Vllm.Multimodal.Inputs.MultiModalFieldElem do
  @moduledoc """
  Represents a keyword argument inside a

  [`MultiModalKwargsItem`][vllm.multimodal.inputs.MultiModalKwargsItem].
  """
  def __snakebridge_python_name__, do: "vllm.multimodal.inputs"
  def __snakebridge_python_class__, do: "MultiModalFieldElem"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `modality` (String.t())
  - `key` (String.t())
  - `data` (((list(((list(term()) | list(term())) | term()) | {term(), term()}) | list(term())) | term())
  | {term(), term()})
  - `field` (term())
  """
  @spec new(
          String.t(),
          String.t(),
          ((list(((list(term()) | list(term())) | term()) | {term(), term()}) | list(term()))
           | term())
          | {term(), term()},
          term(),
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(modality, key, data, field, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [modality, key, data, field], opts)
  end
end
