# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.tasks

defmodule Vllm.Tasks do
  @moduledoc """
  Submodule bindings for `vllm.tasks`.

  ## Version

  - Requested: 0.14.0
  - Observed at generation: 0.14.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Vllm.Tasks.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Vllm.Tasks.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Vllm.Tasks.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Vllm.Tasks.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "vllm.tasks"
  @doc false
  def __snakebridge_library__, do: "vllm"

  @doc """
  Python binding for `vllm.tasks.GenerationTask`.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec generation_task(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def generation_task(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "GenerationTask", [], opts)
  end

  @doc """
  Python module attribute `vllm.tasks.GENERATION_TASKS`.

  ## Returns

  - `tuple()`
  """
  @spec generation_tasks() :: {:ok, tuple()} | {:error, Snakepit.Error.t()}
  def generation_tasks() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "GENERATION_TASKS")
  end

  @doc """
  Python binding for `vllm.tasks.PoolingTask`.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec pooling_task(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def pooling_task(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "PoolingTask", [], opts)
  end

  @doc """
  Python module attribute `vllm.tasks.POOLING_TASKS`.

  ## Returns

  - `tuple()`
  """
  @spec pooling_tasks() :: {:ok, tuple()} | {:error, Snakepit.Error.t()}
  def pooling_tasks() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "POOLING_TASKS")
  end

  @doc """
  Python binding for `vllm.tasks.SupportedTask`.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec supported_task(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def supported_task(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "SupportedTask", [], opts)
  end
end
