# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.tracing

defmodule Vllm.Tracing do
  @moduledoc """
  Submodule bindings for `vllm.tracing`.

  ## Version

  - Requested: 0.14.0
  - Observed at generation: 0.14.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Vllm.Tracing.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Vllm.Tracing.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Vllm.Tracing.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Vllm.Tracing.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "vllm.tracing"
  @doc false
  def __snakebridge_library__, do: "vllm"

  @doc """
  Python module attribute `vllm.tracing._is_otel_imported`.

  ## Returns

  - `boolean()`
  """
  @spec _is_otel_imported() :: {:ok, boolean()} | {:error, Snakepit.Error.t()}
  def _is_otel_imported() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, :_is_otel_imported)
  end

  @doc """
  Python binding for `vllm.tracing.contains_trace_headers`.

  ## Parameters

  - `headers` (term())

  ## Returns

  - `boolean()`
  """
  @spec contains_trace_headers(term(), keyword()) ::
          {:ok, boolean()} | {:error, Snakepit.Error.t()}
  def contains_trace_headers(headers, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :contains_trace_headers, [headers], opts)
  end

  @doc """
  Python binding for `vllm.tracing.extract_trace_context`.

  ## Parameters

  - `headers` (term())

  ## Returns

  - `term()`
  """
  @spec extract_trace_context(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def extract_trace_context(headers, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :extract_trace_context, [headers], opts)
  end

  @doc """
  Python binding for `vllm.tracing.extract_trace_headers`.

  ## Parameters

  - `headers` (term())

  ## Returns

  - `term()`
  """
  @spec extract_trace_headers(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def extract_trace_headers(headers, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :extract_trace_headers, [headers], opts)
  end

  @doc """
  Python binding for `vllm.tracing.get_span_exporter`.

  ## Parameters

  - `endpoint` (term())

  ## Returns

  - `term()`
  """
  @spec get_span_exporter(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def get_span_exporter(endpoint, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :get_span_exporter, [endpoint], opts)
  end

  @doc """
  Python binding for `vllm.tracing.init_tracer`.

  ## Parameters

  - `instrumenting_module_name` (String.t())
  - `otlp_traces_endpoint` (String.t())

  ## Returns

  - `term()`
  """
  @spec init_tracer(String.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def init_tracer(instrumenting_module_name, otlp_traces_endpoint, opts \\ []) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :init_tracer,
      [instrumenting_module_name, otlp_traces_endpoint],
      opts
    )
  end

  @doc """
  Python binding for `vllm.tracing.is_otel_available`.

  ## Returns

  - `boolean()`
  """
  @spec is_otel_available(keyword()) :: {:ok, boolean()} | {:error, Snakepit.Error.t()}
  def is_otel_available(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :is_otel_available, [], opts)
  end

  @doc """
  Python binding for `vllm.tracing.log_tracing_disabled_warning`.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `nil`
  """
  @spec log_tracing_disabled_warning(keyword()) :: {:ok, nil} | {:error, Snakepit.Error.t()}
  def log_tracing_disabled_warning(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :log_tracing_disabled_warning, [], opts)
  end

  @doc """
  Python module attribute `vllm.tracing.logger`.

  ## Returns

  - `term()`
  """
  @spec logger() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def logger() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, :logger)
  end

  @doc """
  Python binding for `vllm.tracing.otel_import_error_traceback`.

  ## Returns

  - `term()`
  """
  @spec otel_import_error_traceback() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), term()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), term(), term()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), term(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), term(), term(), term()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), term(), term(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), term(), term(), term(), term()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), term(), term(), term(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), term(), term(), term(), term(), term()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), term(), term(), term(), term(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(term(), term(), term(), term(), term(), term(), term()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(
          term(),
          term(),
          term(),
          term(),
          term(),
          term(),
          term(),
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(
          term(),
          term(),
          term(),
          term(),
          term(),
          term(),
          term(),
          term()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec otel_import_error_traceback(
          term(),
          term(),
          term(),
          term(),
          term(),
          term(),
          term(),
          term(),
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def otel_import_error_traceback() do
    SnakeBridge.Runtime.call(__MODULE__, :otel_import_error_traceback, [], [])
  end

  def otel_import_error_traceback(opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :otel_import_error_traceback, [], opts)
  end

  def otel_import_error_traceback(arg1) do
    SnakeBridge.Runtime.call(__MODULE__, :otel_import_error_traceback, [arg1], [])
  end

  def otel_import_error_traceback(arg1, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :otel_import_error_traceback, [arg1], opts)
  end

  def otel_import_error_traceback(arg1, arg2) do
    SnakeBridge.Runtime.call(__MODULE__, :otel_import_error_traceback, [arg1, arg2], [])
  end

  def otel_import_error_traceback(arg1, arg2, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :otel_import_error_traceback, [arg1, arg2], opts)
  end

  def otel_import_error_traceback(arg1, arg2, arg3) do
    SnakeBridge.Runtime.call(__MODULE__, :otel_import_error_traceback, [arg1, arg2, arg3], [])
  end

  def otel_import_error_traceback(arg1, arg2, arg3, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :otel_import_error_traceback, [arg1, arg2, arg3], opts)
  end

  def otel_import_error_traceback(arg1, arg2, arg3, arg4) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :otel_import_error_traceback,
      [arg1, arg2, arg3, arg4],
      []
    )
  end

  def otel_import_error_traceback(arg1, arg2, arg3, arg4, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :otel_import_error_traceback,
      [arg1, arg2, arg3, arg4],
      opts
    )
  end

  def otel_import_error_traceback(arg1, arg2, arg3, arg4, arg5) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :otel_import_error_traceback,
      [arg1, arg2, arg3, arg4, arg5],
      []
    )
  end

  def otel_import_error_traceback(arg1, arg2, arg3, arg4, arg5, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :otel_import_error_traceback,
      [arg1, arg2, arg3, arg4, arg5],
      opts
    )
  end

  def otel_import_error_traceback(arg1, arg2, arg3, arg4, arg5, arg6) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :otel_import_error_traceback,
      [arg1, arg2, arg3, arg4, arg5, arg6],
      []
    )
  end

  def otel_import_error_traceback(arg1, arg2, arg3, arg4, arg5, arg6, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :otel_import_error_traceback,
      [arg1, arg2, arg3, arg4, arg5, arg6],
      opts
    )
  end

  def otel_import_error_traceback(arg1, arg2, arg3, arg4, arg5, arg6, arg7) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :otel_import_error_traceback,
      [arg1, arg2, arg3, arg4, arg5, arg6, arg7],
      []
    )
  end

  def otel_import_error_traceback(arg1, arg2, arg3, arg4, arg5, arg6, arg7, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :otel_import_error_traceback,
      [arg1, arg2, arg3, arg4, arg5, arg6, arg7],
      opts
    )
  end

  def otel_import_error_traceback(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :otel_import_error_traceback,
      [arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8],
      []
    )
  end

  def otel_import_error_traceback(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :otel_import_error_traceback,
      [arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8],
      opts
    )
  end

  @doc """
  Python binding for `vllm.tracing.run_once`.

  ## Parameters

  - `f` (term())

  ## Returns

  - `term()`
  """
  @spec run_once(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def run_once(f, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :run_once, [f], opts)
  end

  @doc """
  Python module attribute `vllm.tracing.TRACE_HEADERS`.

  ## Returns

  - `list(term())`
  """
  @spec trace_headers() :: {:ok, list(term())} | {:error, Snakepit.Error.t()}
  def trace_headers() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "TRACE_HEADERS")
  end
end
