# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.scalar_type
# Python class: scalar_types

defmodule Vllm.ScalarType.ScalarTypes do
  @moduledoc """
  Wrapper for Python class scalar_types.
  """
  def __snakebridge_python_name__, do: "vllm.scalar_type"
  def __snakebridge_python_class__, do: "scalar_types"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @spec bfloat16(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def bfloat16(ref) do
    SnakeBridge.Runtime.get_attr(ref, :bfloat16)
  end

  @spec float16(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def float16(ref) do
    SnakeBridge.Runtime.get_attr(ref, :float16)
  end

  @spec float16_e5m10(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def float16_e5m10(ref) do
    SnakeBridge.Runtime.get_attr(ref, :float16_e5m10)
  end

  @spec float16_e8m7(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def float16_e8m7(ref) do
    SnakeBridge.Runtime.get_attr(ref, :float16_e8m7)
  end

  @spec float4_e2m1f(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def float4_e2m1f(ref) do
    SnakeBridge.Runtime.get_attr(ref, :float4_e2m1f)
  end

  @spec float6_e2m3f(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def float6_e2m3f(ref) do
    SnakeBridge.Runtime.get_attr(ref, :float6_e2m3f)
  end

  @spec float6_e3m2f(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def float6_e3m2f(ref) do
    SnakeBridge.Runtime.get_attr(ref, :float6_e3m2f)
  end

  @spec float8_e4m3fn(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def float8_e4m3fn(ref) do
    SnakeBridge.Runtime.get_attr(ref, :float8_e4m3fn)
  end

  @spec float8_e5m2(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def float8_e5m2(ref) do
    SnakeBridge.Runtime.get_attr(ref, :float8_e5m2)
  end

  @spec float8_e8m0fnu(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def float8_e8m0fnu(ref) do
    SnakeBridge.Runtime.get_attr(ref, :float8_e8m0fnu)
  end

  @spec int4(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def int4(ref) do
    SnakeBridge.Runtime.get_attr(ref, :int4)
  end

  @spec int8(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def int8(ref) do
    SnakeBridge.Runtime.get_attr(ref, :int8)
  end

  @spec uint2b2(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def uint2b2(ref) do
    SnakeBridge.Runtime.get_attr(ref, :uint2b2)
  end

  @spec uint3b4(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def uint3b4(ref) do
    SnakeBridge.Runtime.get_attr(ref, :uint3b4)
  end

  @spec uint4(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def uint4(ref) do
    SnakeBridge.Runtime.get_attr(ref, :uint4)
  end

  @spec uint4b8(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def uint4b8(ref) do
    SnakeBridge.Runtime.get_attr(ref, :uint4b8)
  end

  @spec uint8(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def uint8(ref) do
    SnakeBridge.Runtime.get_attr(ref, :uint8)
  end

  @spec uint8b128(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def uint8b128(ref) do
    SnakeBridge.Runtime.get_attr(ref, :uint8b128)
  end
end
