# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.config
# Python class: ECTransferConfig

defmodule Vllm.Config.ECTransferConfig do
  @moduledoc """
  Configuration for distributed EC cache transfer.
  """
  def __snakebridge_python_name__, do: "vllm.config"
  def __snakebridge_python_class__, do: "ECTransferConfig"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Constructs `ECTransferConfig`.

  ## Parameters

  - `dataclass_self__` (term())
  - `args` (term())
  - `kwargs` (term())
  """
  @spec new(term(), term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(dataclass_self__, args, kwargs, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [dataclass_self__, args, kwargs], opts)
  end

  @doc """
  WARNING: Whenever a new field is added to this config,

  ensure that it is included in the factors list if
  it affects the computation graph.

  Provide a hash that uniquely identifies all the configs
  that affect the structure of the computation
  graph from input ids/embeddings to the final hidden states,
  excluding anything before input ids/embeddings and after
  the final hidden states.

  ## Returns

  - `String.t()`
  """
  @spec compute_hash(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def compute_hash(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :compute_hash, [], opts)
  end

  @doc """
  Python method `ECTransferConfig.get_from_extra_config`.

  ## Parameters

  - `key` (term())
  - `default` (term())

  ## Returns

  - `term()`
  """
  @spec get_from_extra_config(SnakeBridge.Ref.t(), term(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def get_from_extra_config(ref, key, default, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_from_extra_config, [key, default], opts)
  end

  @spec ec_buffer_device(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ec_buffer_device(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ec_buffer_device)
  end

  @spec ec_buffer_size(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ec_buffer_size(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ec_buffer_size)
  end

  @spec ec_connector(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ec_connector(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ec_connector)
  end

  @spec ec_connector_module_path(SnakeBridge.Ref.t()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def ec_connector_module_path(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ec_connector_module_path)
  end

  @spec ec_ip(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ec_ip(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ec_ip)
  end

  @spec ec_parallel_size(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ec_parallel_size(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ec_parallel_size)
  end

  @spec ec_port(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ec_port(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ec_port)
  end

  @spec ec_rank(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ec_rank(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ec_rank)
  end

  @spec ec_role(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ec_role(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ec_role)
  end

  @spec engine_id(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def engine_id(ref) do
    SnakeBridge.Runtime.get_attr(ref, :engine_id)
  end

  @spec is_ec_consumer(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def is_ec_consumer(ref) do
    SnakeBridge.Runtime.get_attr(ref, :is_ec_consumer)
  end

  @spec is_ec_producer(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def is_ec_producer(ref) do
    SnakeBridge.Runtime.get_attr(ref, :is_ec_producer)
  end

  @spec is_ec_transfer_instance(SnakeBridge.Ref.t()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def is_ec_transfer_instance(ref) do
    SnakeBridge.Runtime.get_attr(ref, :is_ec_transfer_instance)
  end
end
