# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.config
# Python class: EPLBConfig

defmodule Vllm.Config.EPLBConfig do
  @moduledoc """
  Configuration for Expert Parallel Load Balancing (EP).
  """
  def __snakebridge_python_name__, do: "vllm.config"
  def __snakebridge_python_class__, do: "EPLBConfig"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Constructs `EPLBConfig`.

  ## Parameters

  - `dataclass_self__` (term())
  - `args` (term())
  - `kwargs` (term())
  """
  @spec new(term(), term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(dataclass_self__, args, kwargs, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [dataclass_self__, args, kwargs], opts)
  end

  @doc """
  Python method `EPLBConfig._validate_eplb_config`.

  ## Returns

  - `term()`
  """
  @spec _validate_eplb_config(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _validate_eplb_config(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_validate_eplb_config, [], opts)
  end

  @spec log_balancedness(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def log_balancedness(ref) do
    SnakeBridge.Runtime.get_attr(ref, :log_balancedness)
  end

  @spec log_balancedness_interval(SnakeBridge.Ref.t()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def log_balancedness_interval(ref) do
    SnakeBridge.Runtime.get_attr(ref, :log_balancedness_interval)
  end

  @spec num_redundant_experts(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def num_redundant_experts(ref) do
    SnakeBridge.Runtime.get_attr(ref, :num_redundant_experts)
  end

  @spec policy(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def policy(ref) do
    SnakeBridge.Runtime.get_attr(ref, :policy)
  end

  @spec step_interval(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def step_interval(ref) do
    SnakeBridge.Runtime.get_attr(ref, :step_interval)
  end

  @spec use_async(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def use_async(ref) do
    SnakeBridge.Runtime.get_attr(ref, :use_async)
  end

  @spec window_size(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def window_size(ref) do
    SnakeBridge.Runtime.get_attr(ref, :window_size)
  end
end
