# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.config
# Python class: KVEventsConfig

defmodule Vllm.Config.KVEventsConfig do
  @moduledoc """
  Configuration for KV event publishing.
  """
  def __snakebridge_python_name__, do: "vllm.config"
  def __snakebridge_python_class__, do: "KVEventsConfig"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Constructs `KVEventsConfig`.

  ## Parameters

  - `dataclass_self__` (term())
  - `args` (term())
  - `kwargs` (term())
  """
  @spec new(term(), term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(dataclass_self__, args, kwargs, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [dataclass_self__, args, kwargs], opts)
  end

  @spec buffer_steps(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def buffer_steps(ref) do
    SnakeBridge.Runtime.get_attr(ref, :buffer_steps)
  end

  @spec enable_kv_cache_events(SnakeBridge.Ref.t()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def enable_kv_cache_events(ref) do
    SnakeBridge.Runtime.get_attr(ref, :enable_kv_cache_events)
  end

  @spec endpoint(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def endpoint(ref) do
    SnakeBridge.Runtime.get_attr(ref, :endpoint)
  end

  @spec hwm(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def hwm(ref) do
    SnakeBridge.Runtime.get_attr(ref, :hwm)
  end

  @spec max_queue_size(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def max_queue_size(ref) do
    SnakeBridge.Runtime.get_attr(ref, :max_queue_size)
  end

  @spec publisher(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def publisher(ref) do
    SnakeBridge.Runtime.get_attr(ref, :publisher)
  end

  @spec replay_endpoint(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def replay_endpoint(ref) do
    SnakeBridge.Runtime.get_attr(ref, :replay_endpoint)
  end

  @spec topic(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def topic(ref) do
    SnakeBridge.Runtime.get_attr(ref, :topic)
  end
end
