# Generated by SnakeBridge v0.16.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.config
# Python class: LoadConfig

defmodule Vllm.Config.LoadConfig do
  @moduledoc """
  Configuration for loading the model weights.
  """
  def __snakebridge_python_name__, do: "vllm.config"
  def __snakebridge_python_class__, do: "LoadConfig"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Constructs `LoadConfig`.

  ## Parameters

  - `dataclass_self__` (term())
  - `args` (term())
  - `kwargs` (term())
  """
  @spec new(term(), term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(dataclass_self__, args, kwargs, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [dataclass_self__, args, kwargs], opts)
  end

  @doc """
  Python method `LoadConfig._lowercase_load_format`.

  ## Parameters

  - `load_format` (String.t())

  ## Returns

  - `String.t()`
  """
  @spec _lowercase_load_format(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def _lowercase_load_format(ref, load_format, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_lowercase_load_format, [load_format], opts)
  end

  @doc """
  Python method `LoadConfig._validate_ignore_patterns`.

  ## Parameters

  - `ignore_patterns` (term())

  ## Returns

  - `term()`
  """
  @spec _validate_ignore_patterns(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _validate_ignore_patterns(ref, ignore_patterns, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_validate_ignore_patterns, [ignore_patterns], opts)
  end

  @doc """
  WARNING: Whenever a new field is added to this config,

  ensure that it is included in the factors list if
  it affects the computation graph.

  Provide a hash that uniquely identifies all the configs
  that affect the structure of the computation
  graph from input ids/embeddings to the final hidden states,
  excluding anything before input ids/embeddings and after
  the final hidden states.

  ## Returns

  - `String.t()`
  """
  @spec compute_hash(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def compute_hash(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :compute_hash, [], opts)
  end

  @spec device(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def device(ref) do
    SnakeBridge.Runtime.get_attr(ref, :device)
  end

  @spec download_dir(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def download_dir(ref) do
    SnakeBridge.Runtime.get_attr(ref, :download_dir)
  end

  @spec ignore_patterns(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def ignore_patterns(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ignore_patterns)
  end

  @spec load_format(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def load_format(ref) do
    SnakeBridge.Runtime.get_attr(ref, :load_format)
  end

  @spec model_loader_extra_config(SnakeBridge.Ref.t()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def model_loader_extra_config(ref) do
    SnakeBridge.Runtime.get_attr(ref, :model_loader_extra_config)
  end

  @spec pt_load_map_location(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def pt_load_map_location(ref) do
    SnakeBridge.Runtime.get_attr(ref, :pt_load_map_location)
  end

  @spec safetensors_load_strategy(SnakeBridge.Ref.t()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def safetensors_load_strategy(ref) do
    SnakeBridge.Runtime.get_attr(ref, :safetensors_load_strategy)
  end

  @spec use_tqdm_on_load(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def use_tqdm_on_load(ref) do
    SnakeBridge.Runtime.get_attr(ref, :use_tqdm_on_load)
  end
end
