# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.config
# Python class: SupportsMetricsInfo

defmodule Vllm.Config.SupportsMetricsInfo do
  @moduledoc """
  Base class for protocol classes.

  Protocol classes are defined as::

      class Proto(Protocol):
          def meth(self) -> int:
              ...

  Such classes are primarily used with static type checkers that recognize
  structural subtyping (static duck-typing).

  For example::

      class C:
          def meth(self) -> int:
              return 0

      def func(x: Proto) -> int:
          return x.meth()

      func(C())  # Passes static type check

  See PEP 544 for details. Protocol classes decorated with
  @typing.runtime_checkable act as simple-minded runtime protocols that check
  only the presence of given attributes, ignoring their type signatures.
  Protocol classes can be generic, they are defined as::

      class GenProto[T](Protocol):
          def meth(self) -> T:
              ...
  """
  def __snakebridge_python_name__, do: "vllm.config"
  def __snakebridge_python_class__, do: "SupportsMetricsInfo"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Constructs `SupportsMetricsInfo`.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  Python method `SupportsMetricsInfo.metrics_info`.

  ## Returns

  - `%{optional(String.t()) => String.t()}`
  """
  @spec metrics_info(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, %{optional(String.t()) => String.t()}} | {:error, Snakepit.Error.t()}
  def metrics_info(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :metrics_info, [], opts)
  end

  @spec _abc_impl(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _abc_impl(ref) do
    SnakeBridge.Runtime.get_attr(ref, :_abc_impl)
  end

  @spec _is_protocol(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _is_protocol(ref) do
    SnakeBridge.Runtime.get_attr(ref, :_is_protocol)
  end

  @spec _is_runtime_protocol(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _is_runtime_protocol(ref) do
    SnakeBridge.Runtime.get_attr(ref, :_is_runtime_protocol)
  end
end
