# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.beam_search
# Python class: BeamSearchInstance

defmodule Vllm.BeamSearch.BeamSearchInstance do
  @moduledoc """
  Wrapper for Python class BeamSearchInstance.
  """
  def __snakebridge_python_name__, do: "vllm.beam_search"
  def __snakebridge_python_class__, do: "BeamSearchInstance"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `prompt_tokens` (list(integer()))
  - `lora_request` (term() default: None)
  - `logprobs` (term() default: None)
  - `kwargs` (term())
  """
  @spec new(list(integer()), list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(prompt_tokens, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)

    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [prompt_tokens] ++ List.wrap(args),
      opts
    )
  end
end
