# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.beam_search
# Python class: Logprob

defmodule Vllm.BeamSearch.Logprob do
  @moduledoc """
  Infos for supporting OpenAI compatible logprobs and token ranks.

  Attributes:
      logprob: The logprob of chosen token
      rank: The vocab rank of chosen token (>=1)
      decoded_token: The decoded chosen token index
  """
  def __snakebridge_python_name__, do: "vllm.beam_search"
  def __snakebridge_python_class__, do: "Logprob"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `logprob` (float())
  - `rank` (term() default: None)
  - `decoded_token` (term() default: None)
  """
  @spec new(float(), list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(logprob, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [logprob] ++ List.wrap(args), opts)
  end

  @spec decoded_token(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def decoded_token(ref) do
    SnakeBridge.Runtime.get_attr(ref, :decoded_token)
  end

  @spec rank(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def rank(ref) do
    SnakeBridge.Runtime.get_attr(ref, :rank)
  end
end
