# Generated by SnakeBridge v0.16.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.version

defmodule Vllm.Version do
  @moduledoc """
  Submodule bindings for `vllm.version`.

  ## Version

  - Requested: 0.14.0
  - Observed at generation: 0.14.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Vllm.Version.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Vllm.Version.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Vllm.Version.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Vllm.Version.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "vllm.version"
  @doc false
  def __snakebridge_library__, do: "vllm"

  @doc """
  For the purpose of testing, return a previous minor version number.

  ## Returns

  - `term()`
  """
  @spec _prev_minor_version(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _prev_minor_version(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :_prev_minor_version, [], opts)
  end

  @doc """
  Check whether a given version matches the previous minor version.

  Return True if version_str matches the previous minor version.

  For example - return True if the current version if 0.7.4 and the
  supplied version_str is '0.6'.

  Used for --show-hidden-metrics-for-version.

  ## Parameters

  - `version_str` (term())

  ## Returns

  - `term()`
  """
  @spec _prev_minor_version_was(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _prev_minor_version_was(version_str, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :_prev_minor_version_was, [version_str], opts)
  end
end
