# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.reasoning

defmodule Vllm.Reasoning do
  @moduledoc """
  Submodule bindings for `vllm.reasoning`.

  ## Version

  - Requested: 0.14.0
  - Observed at generation: 0.14.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Vllm.Reasoning.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Vllm.Reasoning.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Vllm.Reasoning.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Vllm.Reasoning.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "vllm.reasoning"
  @doc false
  def __snakebridge_library__, do: "vllm"

  @doc """
  Built-in mutable sequence.

  If no argument is given, the constructor creates a new empty list.
  The argument must be an iterable if specified.

  ## Returns

  - `list(term())`
  """
  @spec __all__() :: {:ok, list(term())} | {:error, Snakepit.Error.t()}
  def __all__() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, :__all__)
  end

  @doc """
  dict() -> new empty dictionary

  dict(mapping) -> new dictionary initialized from a mapping object's
    (key, value) pairs
  dict(iterable) -> new dictionary initialized as if via:
    d = {}
    for k, v in iterable:
        d[k] = v
  dict(**kwargs) -> new dictionary initialized with the name=value pairs
    in the keyword argument list.  For example:  dict(one=1, two=2)

  ## Returns

  - `%{optional(term()) => term()}`
  """
  @spec _reasoning_parsers_to_register() ::
          {:ok, %{optional(term()) => term()}} | {:error, Snakepit.Error.t()}
  def _reasoning_parsers_to_register() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "_REASONING_PARSERS_TO_REGISTER")
  end

  @doc """
  Python binding for `vllm.reasoning.register_lazy_reasoning_parsers`.

  ## Returns

  - `term()`
  """
  @spec register_lazy_reasoning_parsers(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def register_lazy_reasoning_parsers(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :register_lazy_reasoning_parsers, [], opts)
  end
end
