# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.tool_parsers

defmodule Vllm.ToolParsers do
  @moduledoc """
  Submodule bindings for `vllm.tool_parsers`.

  ## Version

  - Requested: 0.14.0
  - Observed at generation: 0.14.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Vllm.ToolParsers.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Vllm.ToolParsers.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Vllm.ToolParsers.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Vllm.ToolParsers.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "vllm.tool_parsers"
  @doc false
  def __snakebridge_library__, do: "vllm"

  @doc """
  Python module attribute `vllm.tool_parsers.__all__`.

  ## Returns

  - `list(term())`
  """
  @spec __all__() :: {:ok, list(term())} | {:error, Snakepit.Error.t()}
  def __all__() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, :__all__)
  end

  @doc """
  Python module attribute `vllm.tool_parsers._TOOL_PARSERS_TO_REGISTER`.

  ## Returns

  - `%{optional(term()) => term()}`
  """
  @spec _tool_parsers_to_register() ::
          {:ok, %{optional(term()) => term()}} | {:error, Snakepit.Error.t()}
  def _tool_parsers_to_register() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "_TOOL_PARSERS_TO_REGISTER")
  end

  @doc """
  Python binding for `vllm.tool_parsers.register_lazy_tool_parsers`.

  ## Returns

  - `term()`
  """
  @spec register_lazy_tool_parsers(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def register_lazy_tool_parsers(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :register_lazy_tool_parsers, [], opts)
  end
end
