# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.tool_parsers
# Python class: ToolParser

defmodule Vllm.ToolParsers.ToolParser do
  @moduledoc """
  Abstract ToolParser class that should not be used directly. Provided

  properties and methods should be used in
  derived classes.
  """
  def __snakebridge_python_name__, do: "vllm.tool_parsers"
  def __snakebridge_python_class__, do: "ToolParser"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `tokenizer` (term())
  """
  @spec new(term(), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(tokenizer, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [tokenizer], opts)
  end

  @doc """
  Static method that used to adjust the request parameters.

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec adjust_request(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def adjust_request(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :adjust_request, [request], opts)
  end

  @doc """
  Static method that should be implemented for extracting tool calls from

  a complete model-generated string.
  Used for non-streaming responses where we have the entire model response
  available before sending to the client.
  Static because it's stateless.

  ## Parameters

  - `model_output` (String.t())
  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec extract_tool_calls(SnakeBridge.Ref.t(), String.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def extract_tool_calls(ref, model_output, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :extract_tool_calls, [model_output, request], opts)
  end

  @doc """
  Instance method that should be implemented for extracting tool calls

  from an incomplete response; for use when handling tool calls and
  streaming. Has to be an instance method because  it requires state -
  the current tokens/diffs, but also the information about what has
  previously been parsed and extracted (see constructor)

  ## Parameters

  - `previous_text` (String.t())
  - `current_text` (String.t())
  - `delta_text` (String.t())
  - `previous_token_ids` (term())
  - `current_token_ids` (term())
  - `delta_token_ids` (term())
  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec extract_tool_calls_streaming(
          SnakeBridge.Ref.t(),
          String.t(),
          String.t(),
          String.t(),
          term(),
          term(),
          term(),
          term(),
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def extract_tool_calls_streaming(
        ref,
        previous_text,
        current_text,
        delta_text,
        previous_token_ids,
        current_token_ids,
        delta_token_ids,
        request,
        opts \\ []
      ) do
    SnakeBridge.Runtime.call_method(
      ref,
      :extract_tool_calls_streaming,
      [
        previous_text,
        current_text,
        delta_text,
        previous_token_ids,
        current_token_ids,
        delta_token_ids,
        request
      ],
      opts
    )
  end

  @spec vocab(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def vocab(ref) do
    SnakeBridge.Runtime.get_attr(ref, :vocab)
  end
end
