# Generated by SnakeBridge v0.15.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: vllm 0.14.0
# Python module: vllm.platforms
# Python class: PlatformEnum

defmodule Vllm.Platforms.PlatformEnum do
  @moduledoc """
  Enum members for `PlatformEnum`.

  Members:
  - `CUDA` = `1`
  - `ROCM` = `2`
  - `TPU` = `3`
  - `XPU` = `4`
  - `CPU` = `5`
  - `OOT` = `6`
  - `UNSPECIFIED` = `7`
  """
  def __snakebridge_python_name__, do: "vllm.platforms"
  def __snakebridge_python_class__, do: "PlatformEnum"
  def __snakebridge_library__, do: "vllm"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Constructs `PlatformEnum`.
  """
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  @spec cpu(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def cpu(ref) do
    SnakeBridge.Runtime.get_attr(ref, :CPU)
  end

  @spec cuda(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def cuda(ref) do
    SnakeBridge.Runtime.get_attr(ref, :CUDA)
  end

  @spec oot(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def oot(ref) do
    SnakeBridge.Runtime.get_attr(ref, :OOT)
  end

  @spec rocm(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def rocm(ref) do
    SnakeBridge.Runtime.get_attr(ref, :ROCM)
  end

  @spec tpu(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def tpu(ref) do
    SnakeBridge.Runtime.get_attr(ref, :TPU)
  end

  @spec unspecified(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def unspecified(ref) do
    SnakeBridge.Runtime.get_attr(ref, :UNSPECIFIED)
  end

  @spec xpu(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def xpu(ref) do
    SnakeBridge.Runtime.get_attr(ref, :XPU)
  end

  @spec name(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def name(ref) do
    SnakeBridge.Runtime.get_attr(ref, :name)
  end

  @spec value(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def value(ref) do
    SnakeBridge.Runtime.get_attr(ref, :value)
  end
end
